In [1]:
from string import ascii_lowercase

In [2]:
import numpy as np

In [3]:
filepath = r"../filestore/words.txt"

In [8]:
np.loadtxt(filepath, dtype='U')

array(['women', 'nikau', 'swack', ..., 'grits', 'kames', 'death'],
      dtype='<U5')

In [38]:
a = np.genfromtxt(
    filepath,
    delimiter=[1,1,1,1,1],
    autostrip=True,
    dtype='U'
)

In [39]:
np.genfromtxt(
    filepath,
    delimiter=[1,1,1,1,1],
    autostrip=True,
    dtype=np.uint8
)

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       ...,
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255]], dtype=uint8)

In [4]:
np.genfromtxt(
    filepath,
    delimiter=[1,1,1,1,1],
    autostrip=True,
    dtype=np.int8
)

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       ...,
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]], dtype=int8)

In [33]:
a

array([['w', 'o', 'm', 'e', 'n'],
       ['n', 'i', 'k', 'a', 'u'],
       ['s', 'w', 'a', 'c', 'k'],
       ...,
       ['g', 'r', 'i', 't', 's'],
       ['k', 'a', 'm', 'e', 's'],
       ['d', 'e', 'a', 't', 'h']], dtype='<U1')

In [28]:
b'\xa3\x8eq\xb5'

b'\xa3\x8eq\xb5'

In [35]:
np.char.encode(a)

array([[b'w', b'o', b'm', b'e', b'n'],
       [b'n', b'i', b'k', b'a', b'u'],
       [b's', b'w', b'a', b'c', b'k'],
       ...,
       [b'g', b'r', b'i', b't', b's'],
       [b'k', b'a', b'm', b'e', b's'],
       [b'd', b'e', b'a', b't', b'h']], dtype='|S1')

In [36]:
b'w' + b'a'

b'wa'

In [31]:
d = np.zeros(a.shape, dtype=np.uint8)

In [40]:
for i, row in enumerate(a):
    for j, c in enumerate(row):
        for u, c1 in enumerate(ascii_lowercase):
            if c1 == c:
                d[i, j] = u

In [41]:
d

array([[22, 14, 12,  4, 13],
       [13,  8, 10,  0, 20],
       [18, 22,  0,  2, 10],
       ...,
       [ 6, 17,  8, 19, 18],
       [10,  0, 12,  4, 18],
       [ 3,  4,  0, 19,  7]], dtype=uint8)

In [42]:
np.save(r"../filestore/words.npy", d)

In [23]:
a.shape

(12947, 5)

In [ ]:
help(np

In [4]:
with open(filepath, 'r') as f:
    l = f.readlines()

In [6]:
l[:5]

['women\n', 'nikau\n', 'swack\n', 'feens\n', 'fyles\n']

In [7]:
l[-5:]

['motor\n', 'geums\n', 'grits\n', 'kames\n', 'death']